/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JapaneseKeyBoard: typeof import('./src/components/JapaneseKeyBoard.vue')['default']
    KanjiCard: typeof import('./src/components/KanjiCard.vue')['default']
    KanjiCard_backup: typeof import('./src/components/KanjiCard_backup.vue')['default']
    KeyButton: typeof import('./src/components/KeyButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
